[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "10a93f722f7f4061b188b8f1f516d231020484146f18452b3a47926574926e0d"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "6fe302ab9dee0955ebb66a8f40ee0389019d7452"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "9e6218c5203c31e76e9a28fc835ea4a39f29ddcfd92f7ecfdfc3c75c1bc36dbe"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "482d950b48d363dcc167debccd2737617c36a02aa1c7c5631773ca930915c70f"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "92a83665adc9969ef58501a0fc8d2b57e7ba6b5866a2e2ef4a9b4e5fc7d0d2fb"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-armv7l-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4e616b356de2b2854468e3f21696891ec8b8b8ebc8aea9305c5335d7ed934a5a"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "e360eff259bef4eeaabbde1fba8704afcc840fdd38c415cda52d84b7ef09b25b"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "21ca949bd9e8166953c4835b0e41bda0bd0d6b3e2ba6f5b1bcee2ac142aea8fc"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "2fd15f75507ec6538ee2ef956b844d7a176c61286625665461c129b8d6a16855"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "61394a7f86658f9019fd45c985a3805d798c19e7232344df2c6a07d811419159"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-armv7l-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "db945d1e8b4db5685d20e55ac765d5f5834c43a0"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "3c9215ed053e53f2da7b6a3c98519cd290fdce4ea1c23592e7ba8db871cfefc1"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "db945d1e8b4db5685d20e55ac765d5f5834c43a0"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "caebf3ab2d255174615a05be0c22aff8b43b7a99484e3fc96a0d11f558ad23c5"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-aarch64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "3cade26e84e4fc38a3e42dac77570f3b2fd51216"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "e2ed5e21c2e64c118433b65f0f47bbff335ed4dfe7fb2f5d640ada08185bb7bd"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "69870b7b1a1c9363965bdc51744d47fc6d06cf87"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "09f35f9508050729a0c47668a7a8ab84aaf88722010fa28615bf24e4af0f61f3"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "ae030aa5873eb5e46fc1884fa4c04a5e3394828b"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "8758d12020c04a9960f878b509b4d4ee79b5e3f8a8a98add47b3209c0cd4e38b"
    url = "https://github.com/rben01/VegaLiteBuilder/releases/download/v4.0.1/vegaliteassets-4.0.1-x86_64-w64-mingw32.tar.gz"
