var documenterSearchIndex = {"docs": [

{
    "location": "index.html#",
    "page": "Introduction",
    "title": "Introduction",
    "category": "page",
    "text": "VegaLite.jl enables the generation of Vega-Lite plots from Julia.Vega-Lite (http://vega.github.io/vega-lite/) is a visualization grammar describing mappings from data to graphical properties (marks, axes, scales, ..). For rendering it uses pre-defined design rules that keep the visualization specification succinct while still leaving user control.Vega-Lite supports :data transformation, sorting, filtering and grouping,\naggregation, binning, and simple statistical analysis (mean, std, var, count, ..).\nplots can be faceted, layered and stacked vertically or horizontally.To install the package run Pkg.add(\"VegaLite\")."
},

{
    "location": "index.html#Principles-1",
    "page": "Introduction",
    "title": "Principles",
    "category": "section",
    "text": "The package is essentially a thin layer translating Julia statements to the Vega-Lite visualization specification format.Vega-Lite uses the JSON format for its specification. Typical Vega-Lite specs look like :{\n  \"encoding\": {\n    \"x\": {\n      \"bin\": {\n        \"maxbins\": 10\n      },\n      \"field\": \"IMDB_Rating\",\n      \"type\": \"quantitative\"\n    },\n    \"size\": {\n      \"aggregate\": \"count\",\n      \"type\": \"quantitative\"\n    },\n    \"y\": {\n      \"bin\": {\n        \"maxbins\": 10\n      },\n      \"field\": \"Rotten_Tomatoes_Rating\",\n      \"type\": \"quantitative\"\n    }\n  },\n  \"data\": {\n    \"url\": \"https://raw.githubusercontent.com/vega/new-editor/master/data/movies.json\"\n  },\n  \"mark\": {\n    \"type\": \"circle\"\n  }\n}This visualization specification can be generated from within Julia by:data(url=\"https://raw.githubusercontent.com/vega/new-editor/master/data/movies.json\") |>\n  markcircle() |>\n  encoding(xquantitative(vlbin(maxbins=10), field=:IMDB_Rating),\n           yquantitative(vlbin(maxbins=10), field=:Rotten_Tomatoes_Rating),\n           sizequantitative(aggregate=:count))Finally the plot generated by the vega-lite library will  look like :(Image: plot1)"
},

{
    "location": "quick.html#",
    "page": "Quick Tour",
    "title": "Quick Tour",
    "category": "page",
    "text": ""
},

{
    "location": "quick.html#Quick-tour-1",
    "page": "Quick Tour",
    "title": "Quick tour",
    "category": "section",
    "text": ""
},

{
    "location": "quick.html#Simple-scatter-plot-1",
    "page": "Quick Tour",
    "title": "Simple scatter plot",
    "category": "section",
    "text": "Use functions linked by the |> operator to build your visuialization incrementally. VegaLite.jl can use DataFrames or DataTables as sources for data. For a scatter plot, specify that the mark should a point by markpoint(), then how the data in the DataFrame mpg (fields :Cty, :Hwy and :Manufacturer) should be connected to the encoding channels (x, y and color respectively). Finally, global configuration options are provided in a config function (type ? config`to see all the options).using RDatasets\n\nmpg = dataset(\"ggplot2\", \"mpg\") # load the \'mpg\' dataframe\n\nmpg |> # start with the data source (here a DataFrame)\n  markpoint() |>\n  encoding(xquantitative(field=:Cty, axis=nothing),\n           yquantitative(field=:Hwy, vlscale(zero=false)),\n           colornominal(field=:Manufacturer)) |>    # bind color to :Manufacturer, nominal scale\n  config(vlcell(width=350, height=400))(Image: plot1)An alternative, more julian syntax, without the piping operator is also valid. The preceding statement can just as well be written :plot(data(mpg),\n     markpoint(),\n     encoding(xquantitative(field=:Cty, axis=nothing),\n              yquantitative(field=:Hwy, vlscale(zero=false)),\n              colornominal(field=:Manufacturer)),\n     config(vlcell(width=350, height=400)))"
},

{
    "location": "quick.html#Stacking-multiple-plots-with-hconcat()-or-vconcat()-1",
    "page": "Quick Tour",
    "title": "Stacking multiple plots with hconcat() or vconcat()",
    "category": "section",
    "text": "Several independant plots can be concatenated vertically or horizontally :using RDatasets\n\nmpg = dataset(\"ggplot2\", \"mpg\") # load the \'mpg\' dataframe\n\nr1 = markline() |>\n     encoding(xquantitative(field=:Cty, axis=nothing),\n              yquantitative(field=:Hwy, vlscale(zero=false)),\n              colornominal(field=:Manufacturer)) ;\n\nr2 = markrect() |>\n      encoding(xquantitative(field=:Displ, vlbin(maxbins=5)),\n               yquantitative(field=:Hwy, vlbin(maxbins=5)),\n               colornominal(field=:Manufacturer)) ;\n\nmpg |>\n  vconcat(r1) |>\n  vconcat(r2) |>\n  config(vlcell(width=400))(Image: plot2)"
},

{
    "location": "quick.html#Using-layer()-to-surimpose-several-plots-1",
    "page": "Quick Tour",
    "title": "Using layer() to surimpose several plots",
    "category": "section",
    "text": "When several marks need to shown on the same visualization, use the layer() function :using DataFrames\n\ndf  = DataFrame(x=[0:5;], y=rand(6))\n\nencx = xquantitative(field=:x)\nency = yquantitative(field=:y)\n\ndf |>\n  plot(width=500) |>\n  layer(markline(interpolate=\"linear\"),\n        encoding(encx, ency, vlcolor(value=\"green\"))) |>\n  layer(markline(interpolate=\"basis\"),\n        encoding(encx, ency, vlcolor(value=\"red\"))) |>\n  layer(markpoint(), encoding(encx, ency, vlcolor(value=\"black\")))(Image: plot4)"
},

{
    "location": "quick.html#Using-repeat()-to-facet-a-plot-by-data-fields-1",
    "page": "Quick Tour",
    "title": "Using repeat() to facet a plot by data fields",
    "category": "section",
    "text": "To create a facet plot with encoding channels cycled through a list of data fields use the repeat() function :using Distributions, DataTables\n\nxs = rand(Normal(), 100, 3)\ndt = DataTable(a = xs[:,1] + xs[:,2] .^ 2,\n               b = xs[:,3] .* xs[:,2],\n               c = xs[:,3] .+ xs[:,2])\n\ndt |>\n  repeat(column = [:a, :b, :c], row = [:a, :b, :c]) |>\n  config(vlcell(width=100, height=100)) |>\n  spec(markpoint(),\n       encoding(xquantitative(vlfield(repeat=:column)),\n                yquantitative(vlfield(repeat=:row))))(Image: plot3)"
},

{
    "location": "vlspec.html#",
    "page": "Vega-lite specifications",
    "title": "Vega-lite specifications",
    "category": "page",
    "text": ""
},

{
    "location": "vlspec.html#Vega-lite-specifications-1",
    "page": "Vega-lite specifications",
    "title": "Vega-lite specifications",
    "category": "section",
    "text": "A vega-lite specification is represented as a VLSpec object in julia. There are multiple ways to create a VLSpec object. The previous section demonstrated the use of the julia API to create these specification objects. This section describes three additional ways to create and interact with these specification objects: the vl string macro, functions that load and save specifications from and to disc, and the DataVoyager.jl package."
},

{
    "location": "vlspec.html#The-vl-string-macro-1",
    "page": "Vega-lite specifications",
    "title": "The vl string macro",
    "category": "section",
    "text": "One can embed a JSON vega-lite specification directly in julia code by using the vl string macro:using VegaLite\n\nspec = vl\"\"\"\n{\n  \"$schema\": \"https://vega.github.io/schema/vega-lite/v2.json\",\n  \"description\": \"A simple bar chart with embedded data.\",\n  \"data\": {\n    \"values\": [\n      {\"a\": \"A\",\"b\": 28}, {\"a\": \"B\",\"b\": 55}, {\"a\": \"C\",\"b\": 43},\n      {\"a\": \"D\",\"b\": 91}, {\"a\": \"E\",\"b\": 81}, {\"a\": \"F\",\"b\": 53},\n      {\"a\": \"G\",\"b\": 19}, {\"a\": \"H\",\"b\": 87}, {\"a\": \"I\",\"b\": 52}\n    ]\n  },\n  \"mark\": \"bar\",\n  \"encoding\": {\n    \"x\": {\"field\": \"a\", \"type\": \"ordinal\"},\n    \"y\": {\"field\": \"b\", \"type\": \"quantitative\"}\n  }\n}\n\"\"\"The resulting VLSpec object is indistinguishable from one that is created via the julia API.The main benefit of this approach is that one can directly leverage JSON vega-lite examples and code."
},

{
    "location": "vlspec.html#Loading-and-saving-vega-lite-specifications-1",
    "page": "Vega-lite specifications",
    "title": "Loading and saving vega-lite specifications",
    "category": "section",
    "text": "The loadspec and savespec function can be used to load and save vega-lite specifications from disc. The following example loads a vega-lite specification from a file named myfigure.vegalite:using VegaLite\n\nspec = loadspec(\"myfigure.vegalite\")To save a VLSpec to a file on disc, use the savespec function:using VegaLite\n\nspec = ... # Aquire a spec from somewhere\n\nsavespec(\"myfigure.vegalite\", spec)"
},

{
    "location": "vlspec.html#[DataVoyager.jl](https://github.com/davidanthoff/DataVoyager.jl)-1",
    "page": "Vega-lite specifications",
    "title": "DataVoyager.jl",
    "category": "section",
    "text": "The DataVoyager.jl package provides a graphical UI for data exploration that is based on vega-lite. One can use that tool to create a figure in the UI, and then export the corresponding vega-lite specification for use with this package here."
},

{
    "location": "global.html#",
    "page": "Global settings",
    "title": "Global settings",
    "category": "page",
    "text": ""
},

{
    "location": "global.html#VegaLite.renderer",
    "page": "Global settings",
    "title": "VegaLite.renderer",
    "category": "function",
    "text": "renderer()\n\nshow current rendering mode (svg or canvas)\n\nrenderer(::Symbol)\n\nset rendering mode (svg or canvas)\n\n\n\n"
},

{
    "location": "global.html#VegaLite.actionlinks",
    "page": "Global settings",
    "title": "VegaLite.actionlinks",
    "category": "function",
    "text": "actionlinks()::Bool\n\nshow if plots will have (true) or not (false) the action links displayed\n\nactionlinks(::Bool)\n\nindicate if actions links should be dislpayed under the plot\n\n\n\n"
},

{
    "location": "global.html#Global-settings-1",
    "page": "Global settings",
    "title": "Global settings",
    "category": "section",
    "text": "rendereractionlinksjunoplotpane"
},

{
    "location": "output.html#",
    "page": "Outputs",
    "title": "Outputs",
    "category": "page",
    "text": ""
},

{
    "location": "output.html#Output-1",
    "page": "Outputs",
    "title": "Output",
    "category": "section",
    "text": ""
},

{
    "location": "output.html#On-evaluation-1",
    "page": "Outputs",
    "title": "On evaluation",
    "category": "section",
    "text": ""
},

{
    "location": "output.html#VegaLite.pdf",
    "page": "Outputs",
    "title": "VegaLite.pdf",
    "category": "function",
    "text": "pdf(filename::AbstractString, v::VLSpec{:plot})\n\nSave the plot v as a pdf file with name filename.\n\n\n\n"
},

{
    "location": "output.html#VegaLite.png",
    "page": "Outputs",
    "title": "VegaLite.png",
    "category": "function",
    "text": "png(filename::AbstractString, v::VLSpec{:plot})\n\nSave the plot v as a png file with name filename.\n\n\n\n"
},

{
    "location": "output.html#VegaLite.svg",
    "page": "Outputs",
    "title": "VegaLite.svg",
    "category": "function",
    "text": "svg(filename::AbstractString, v::VLSpec{:plot})\n\nSave the plot v as a svg file with name filename.\n\n\n\n"
},

{
    "location": "output.html#VegaLite.savefig",
    "page": "Outputs",
    "title": "VegaLite.savefig",
    "category": "function",
    "text": "savefig(filename::AbstractString, v::VLSpec{:plot})\n\nSave the plot v as a file with name filename. The file format will be picked based on the extension of the filename.\n\n\n\n"
},

{
    "location": "output.html#Saving-to-a-file-1",
    "page": "Outputs",
    "title": "Saving to a file",
    "category": "section",
    "text": "pdf\npng\nsvgOr you can use a single saving functions that guesses the image format from the extension of the provided filenamesavefig"
},

{
    "location": "functions.html#",
    "page": "API reference",
    "title": "API reference",
    "category": "page",
    "text": ""
},

{
    "location": "functions.html#Functions-1",
    "page": "API reference",
    "title": "Functions",
    "category": "section",
    "text": ""
},

{
    "location": "functions.html#st-level-functions-1",
    "page": "API reference",
    "title": "1st level functions",
    "category": "section",
    "text": "plot\ndata\ntransform\nvlmark\nencoding\nconfig\nlayer\nfacet\nrepeat\nhconcat\nvconcat\nspec\nselection"
},

{
    "location": "functions.html#Mark-functions-1",
    "page": "API reference",
    "title": "Mark functions",
    "category": "section",
    "text": "vltick\nvlbar"
},

{
    "location": "functions.html#Encoding-channels-1",
    "page": "API reference",
    "title": "Encoding channels",
    "category": "section",
    "text": "vlx\nvly\nvlx2\nvly2\nvlcolor\nvlsize\nvlrow\nvlcolumn\nvltooltip\nvlorder\nvldetail\nvlshape\nvlopacity\nvltext"
},

{
    "location": "functions.html#nd-level-functions-1",
    "page": "API reference",
    "title": "2nd level functions",
    "category": "section",
    "text": "vlaxis\nvlscale\nvlsort\nvlformat\nvllegend\nvltitle\nvlvalues\nvlfrom\nvloneOf\nvloverlay\nvlcondition\nvlencode\nvlequal\nvlaxisBand\nvlfilter\nvlscheme\nvlfield\nvlpadding\nvlheader\nvlinterval\nvlbin\nvlbind\nvlsummarize\nvldomain\nvlresolve\nvlcell"
},

]}
